# Generated by Django 5.2.17 on 2026-10-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeracao', models.CharField(max_length=10)),
                ('preco_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
